spring:
  application:
    name: file-processor
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      username: admin
      password: password
      fail-fast: true
  profiles:
    active: local